### ISSUE TITLE
Update the project to use jakarta namespace

### ISSUE THREAD

**Issue by zeppelinux** [apimatic/core-lib-java#66]
I'm trying to use Square SDK in my Quarkus 3 project. Because of Quarkus 3 is compiled for jakarta namespace and Square SDK is using apimatic core, which uses javax - it fails on:

```
Caused by: java.lang.ClassNotFoundException: javax.json.JsonException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
```
To reproduce:
1. Check out this project https://github.com/zeppelinux/square-okhttp-problem
2. mvn clean compile quarkus:dev
3. Navigate to http://localhost:8080/hello

To resolve it there is a need to update the apimatic/core-lib-java to use jakarta instead of javax.

**Comment by zeppelinux** [comment]
I forked it and ported to jakarta here https://github.com/zeppelinux/core-lib-java/tree/feature/port-to-jakarta
Tests are run green from IDE, but fail from cmd line on some jacoco class version exception.

**Comment by hamzashoukat94** [comment]
Hi @zeppelinux
Thanks for opening the issues. I appreciate that you have also suggested a workaround for others!
Switching from `javax` to `jakarta` isn't on the immediate roadmap for this library.  We'll let you know once it is prioritized.
Thanks!
